name: ActionNow
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Hive for local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # BLoC for state management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  firebase_core: ^2.0.0
  firebase_database: ^10.0.0
  firebase_auth: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Hive code generator
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
flutter:
  uses-material-design: true
